// rolesData.js

export const roles = [
  //Morgan Stanley
  {
    company: "S9 Technologies inc.",
    client: "Morgan Stanley",
    role: "Senior Frontend Developer",
    duration: "January 2025 to Till Date",
    description: `Developed a secure, high-performance internal web App for Morgan Stanley's global finance teams to visualize and manage real-time financial data. As Senior Frontend Developer, used to design and implementation, contributing to the hybrid Angular-React architecture`,
    responsibilities: [
      `Designed and implemented responsive UI using React, Angular, Material UI, Tailwind CSS, and Bootstrap.`,
      `Architected scalable and modular React applications using Hooks, Context API, and Redux Toolkit, ensuring maintainability and reusability.`,
      `Utilized AgGrid for real-time data grids with features like infinite scrolling, custom cell rendering, and server-side pagination.`,
      `Integrated advanced state management using NgRx (Angular), RxJS, Redux, Redux Toolkit, and Context API for seamless user experience and data flow.`,
      `Integrated Java and Spring Boot microservices for authentication, authorization (using JWT), and data persistence.`,
      `Modeled and managed dynamic data structures using MongoDB, with optimized queries for high-performance dashboard rendering.`,
      `Built and deployed proof-of-concept features, integrating secure RESTful APIs (including failure handling) and implementing unit testing in React with Jest and Testing Library to ensure stability and test coverage.`,
      `Collaborated using Git, GitHub, GitLab, Bitbucket, and GitHub Desktop for version control and code review practices.`,
      `Used Visual Studio Code and Eclipse for daily development, debugging, and integration tasks.`,
      `Implemented JWT-based authentication, input validation, and access control for user role management.`,
      `Optimized bundle size, lazy loading, and component reusability for improved application performance.`,
      `Boosted data rendering performance by 40% through AgGrid optimization and effective memoization techniques.`,
      `Reduced API response time by 30% by refactoring backend services and improving MongoDB indexing.`,
      `Improved user adoption by 60% with enhanced UI/UX, accessibility, and cross-browser compatibility.
  h the APIs.`,
    ],
    tools: [
      "Angular",
      "React",
      "TypeScript",
      "JavaScript (ES6+)",
      "HTML5",
      "CSS3",
      "Bootstrap",
      "Material UI",
      "Tailwind CSS",
      "AgGrid",
      "NgRx",
      "RxJS",
      "Redux",
      "Redux Toolkit",
      "Context API",
      "Node.js",
      "Express.js",
      "Java",
      "Spring Boot",
      "RESTful APIs",
    ],
  },

  //Ceva Logistics
  // {
  //   company: "",
  //   client: "Ceva Logistics",
  //   role: "Senior Frontend Developer",
  //   duration: "January 2025 to Till Date",
  //   description:
  //     "The primary goal of the project is to ensure real-time freight management, providing a seamless integration between various systems involved in logistics. The system aims to provide both internal and external visibility, enhance communication across global data centers, and ensure that updates related to shipments are accurate and timely.",
  //   responsibilities: [
  //     "Developed the application using modern front-end technologies, including Angular 15, TypeScript, JavaScript (ES6+), CSS3, and HTML5.",
  //     "Built dynamic and interactive web pages using HTML5, CSS3, and JavaScript (ES6+), implementing best UI/UX practices.",
  //     "Utilized Agile methodologies and worked with Jira to track tasks, bugs, and feature implementations effectively.",
  //     "Planned and developed user stories assigned by the client, ensuring successful sprint completion and delivering demos at the end of each sprint cycle.",
  //     "Enhanced accessibility by leveraging Angular Material’s built-in ARIA support and customizing components for screen-reader support and keyboard operability.",
  //     "Implemented business logic using Angular components, services, models, RxJS, and dependency injection, following OOP principles and modular development practices.",
  //     "Collaborated with back-end developers to ensure smooth API integration, ensuring that front-end interfaces interact effectively with the microservices architecture and databases.",
  //     "Optimized application performance by implementing lazy loading, change detection strategies (OnPush), and efficient API handling using RxJS.",
  //     "Implemented unit and integration tests using Jasmine and Karma for Angular components and JUnit and Mockito for backend logic.",
  //     "Collaborated with designers to ensure the UI design aligns with the user-centric approach and overall business requirements.",
  //     "Built responsive layouts using modern CSS frameworks (e.g., Flexbox, CSS Grid) to ensure optimal user experiences across all screen sizes.",
  //     "Implemented error handling and display user-friendly messages to ensure smooth interactions with the APIs.",
  //   ],
  //   tools: [
  //     "Angular 15",
  //     "TypeScript",
  //     "JavaScript (ES6+)",
  //     "HTML5",
  //     "CSS3",
  //     "Bootstrap",
  //     "Material UI",
  //     "Tailwind CSS",
  //     "NgRx",
  //     "RxJS",
  //     "Java",
  //     "Spring Boot",
  //     "RESTful APIs",
  //     "JWT",
  //     "JSON",
  //     "Git",
  //     "GitHub",
  //     "GitLab",
  //     "Bitbucket",
  //     "GitHub Desktop",
  //     "Microsoft Windows",
  //   ],
  // },

  {
    company: "Birlasoft",
    client: "Arch Insurance Group Inc.",
    role: "Front End Developer",
    duration: "April 2023 to December 2024",
    description:
      "Re-architecting the legacy application to align with modern architectural standards and improving usability and performance.",
    responsibilities: [
      "Designed and developed scalable applications using Angular 14, HTML5, CSS3, and Ag Grid.",
      "Enhanced UI with Material UI components and Bootstrap for responsiveness.",
      "Integrated Power BI dashboards for seamless data visualization.",
      "Implemented reusable modular components for maintainability.",
      "Collaborated with cross-functional teams to deliver solutions.",
      "Integrated RESTful APIs using HttpClientModule and RxJS.",
      "Developed complex forms and export features (PDF, CSV) with AG Grid.",
      "Implemented custom filtering, sorting, and inline editing within AG Grid.",
    ],
    tools: [
      "Angular 14",
      "HTML 5",
      "CSS 3",
      "Angular Material",
      "Ag Grid",
      "Git",
      "Jira",
    ],
  },
  {
    company: "Birlasoft",
    client: "Johnson & Johnson",
    role: "UI Developer",
    duration: "Sept 2021 to March 2023",
    description:
      "Developed NELP, a product suite that accelerates clinical and business operations, handling both structured and unstructured data.",
    responsibilities: [
      "Implemented a user-friendly, responsive application using Bootstrap 5, HTML 5, and CSS3.",
      "Created dynamic UI elements like carousels, tabs, and forms to enhance user interaction.",
      "Consumed and processed backend API data for functionalities like Adverse Events, Translate, and Summarizer.",
      "Optimized application speed by minimizing DOM manipulations and implementing lazy loading.",
      "Built complex forms with Angular Reactive and Template-Driven Forms, incorporating validation.",
      "Utilized RxJS for real-time data updates and component communication.",
      "Handled API failures with Angular’s ErrorInterceptor and Toast notifications.",
      "Followed Agile methodology, tracked tasks with Jira, and maintained version control with Git.",
    ],
    tools: ["Angular 13", "HTML 5", "CSS 3", "Bootstrap 5", "Git", "Jira"],
  },
  {
    company: "Techdeets Info Solutions Pvt Ltd",

    client: "USM Systems",
    role: "UI Developer",
    duration: "Oct 2020 to Sep 2021",
    description:
      "Consultant Information Management System is an Angular-based web application that streamlines consultant management by storing and accessing profiles, enabling easy search for consultants, managing assignments, tracking project allocations, and generating reports.",
    responsibilities: [
      "Designed and developed the user interface using React.js, creating reusable and modular components.",
      "Utilized React Hooks (useState, useEffect, useRef, useCallback) to manage state and lifecycle methods.",
      "Implemented React Router to manage navigation between views.",
      "Leveraged React’s Context API for global state management, enabling seamless data sharing.",
      "Built a custom component library using React and Styled-Components.",
      "Integrated RESTful APIs using Axios to fetch and update data from the backend.",
      "Developed dynamic forms using React Hook Form and Yup for validation.",
      "Optimized performance with React.memo, useMemo, and useCallback.",
      "Implemented unit tests using Jest and React Testing Library, conducted end-to-end testing with Cypress.",
    ],
    tools: ["React", "JavaScript", "Axios", "HTML 5", "CSS 3"],
  },
  {
    company: "Techdeets Info Solutions Pvt Ltd",

    client: "HIGHIQ Robotics ",
    role: "UI Developer",
    duration: "April 2019 to Oct 2020",
    description:
      "Parivartan - Dream of India is an initiative to make UPSC guidance accessible and affordable for aspiring civil servants.",
    responsibilities: [
      "Designed and developed scalable front-end architecture using Angular11.",
      "Built reusable and dynamic Angular components to streamline development.",
      "Implemented state management using Angular services and RxJS.",
      "Configured Angular Router for smooth navigation.",
      "Ensured cross-browser compatibility and responsive design.",
      "Developed and consumed RESTful APIs and GraphQL endpoints.",
      "Implemented dynamic, validated forms with Angular Forms.",
      "Collaborated with designers to implement responsive interfaces using Angular Material.",
      "Wrote unit tests for Angular components and services using Jasmine and Karma.",
      "Deployed applications to Azure cloud using PaaS services.",
    ],
    tools: [
      "Angular 11",
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "RxJS",
      "Angular Material",
      "RESTful APIs",
      "Jasmine",
      "Karma",
    ],
  },
  {
    company: "Apollo Groups",

    client: "Apollo Groups",
    role: "Junior Web Developer",
    duration: "May 2016 to April 2019",
    description:
      "Healthcare Patient Management System is a web application that streamlines patient records management, ensuring accessibility for healthcare professionals.",
    responsibilities: [
      "Designed and developed mobile-friendly web pages using HTML5, CSS3, and JavaScript.",
      "Collaborated with designers and backend developers to create responsive UI components.",
      "Troubleshot and debugged front-end development issues.",
      "Worked with the testing team to ensure functionality of UI components.",
      "Stayed updated with the latest front-end development trends.",
    ],
    tools: ["HTML5", "CSS3", "JavaScript"],
  },
];
