// rolesData.js

export const roles = [
  {
    company: "S9 Technologies inc.",
    client: "Ceva Logistics",
    role: "Senior Frontend Developer",
    duration: "January 2025 to Till Date",
    description:
      "The project aims to enhance real-time freight management, improve communication across global data centers, and ensure accurate and timely updates on shipments.",
    responsibilities: [
      "Developed applications using modern front-end technologies, including Angular 15, TypeScript, JavaScript (ES6+), CSS3, and HTML5.",
      "Built dynamic and interactive web pages using HTML5, CSS3, and JavaScript (ES6+), implementing best UI/UX practices.",
      "Utilized Agile methodologies and worked with Jira to track tasks, bugs, and feature implementations effectively.",
      "Planned and developed user stories assigned by the client, ensuring successful sprint completion and delivering demos at the end of each sprint cycle.",
      "Implemented business logic using Angular components, services, models, RxJS, and dependency injection, following OOP principles and modular development practices.",
      "Collaborated with back-end developers to ensure smooth API integration, ensuring front-end interfaces interact effectively with microservices architecture and databases.",
      "Optimized application performance by implementing lazy loading, change detection strategies (OnPush), and efficient API handling using RxJS.",
      "Implemented unit and integration tests using Jasmine and Karma for Angular components, and JUnit and Mockito for backend logic.",
      "Collaborated with designers to ensure the UI design aligns with the user-centric approach and overall business requirements.",
      "Built responsive layouts using modern CSS frameworks (e.g., Flexbox, CSS Grid) to ensure optimal user experiences across all screen sizes.",
      "Implemented error handling and displayed user-friendly messages to ensure smooth interactions with the APIs.",
    ],
    tools: [
      "Angular",
      "React",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "JSON",
      "MongoDB",
      "Bootstrap",

      "Material UI",
      "Tailwind CSS",
    ],
  },
  {
    company: "Birlasoft",
    client: "BNY Mellon Corporation",
    role: "Senior Front End Developer",
    duration: "June 2024 to Dec 2024",
    description:
      "Developing a modern, user-friendly banking platform focusing on account management, transactions, and security, with seamless backend integration for real-time financial operations.",
    responsibilities: [
      "Developed responsive UI using Angular 14, Angular Material, and Bootstrap.",
      "Implemented routing with lazy loading and preloading for performance optimization.",
      "Created reusable dynamic components using Angular's component architecture and RxJS.",
      "Integrated backend services via RESTful APIs using HttpClientModule and RxJS.",
      "Implemented state management with NgRx and BehaviorSubject.",
      "Handled form validation with Reactive Forms and custom validators.",
      "Implemented role-based authorization using Angular Guards and JWT authentication.",
      "Developed RESTful APIs for authentication, account management, and transactions.",
      "Integrated Spring Security with JWT authentication on the backend.",
      "Conducted end-to-end testing with Cypress and Protractor.",
      "Deployed using AWS (S3, CloudFront) and configured CI/CD with GitHub Actions.",
    ],
    tools: [
      "Angular 14",
      "Material",
      "NgRx",
      "RxJS",
      "Bootstrap",
      "JWT Authentication",
      "Spring Boot",
      "AWS",
      "GitHub Actions",
      "Jasmine",
      "Karma",
      "Cypress",
      "Protractor",
    ],
  },
  {
    company: "Birlasoft",
    client: "Arch Insurance Group Inc.",
    role: "Front End Developer",
    duration: "April 2023 to June 2024",
    description:
      "Re-architecting the legacy application to align with modern architectural standards and improving usability and performance.",
    responsibilities: [
      "Designed and developed scalable applications using Angular 14, HTML5, CSS3, and Ag Grid.",
      "Enhanced UI with Material UI components and Bootstrap for responsiveness.",
      "Integrated Power BI dashboards for seamless data visualization.",
      "Implemented reusable modular components for maintainability.",
      "Collaborated with cross-functional teams to deliver solutions.",
      "Integrated RESTful APIs using HttpClientModule and RxJS.",
      "Developed complex forms and export features (PDF, CSV) with AG Grid.",
      "Implemented custom filtering, sorting, and inline editing within AG Grid.",
    ],
    tools: [
      "Angular 14",
      "HTML 5",
      "CSS 3",
      "Angular Material",
      "Ag Grid",
      "Git",
      "Jira",
    ],
  },
  {
    company: "Birlasoft",
    client: "Johnson & Johnson",
    role: "UI Developer",
    duration: "Sept 2021 to March 2023",
    description:
      "Developed NELP, a product suite that accelerates clinical and business operations, handling both structured and unstructured data.",
    responsibilities: [
      "Implemented a user-friendly, responsive application using Bootstrap 5, HTML 5, and CSS3.",
      "Created dynamic UI elements like carousels, tabs, and forms to enhance user interaction.",
      "Consumed and processed backend API data for functionalities like Adverse Events, Translate, and Summarizer.",
      "Optimized application speed by minimizing DOM manipulations and implementing lazy loading.",
      "Built complex forms with Angular Reactive and Template-Driven Forms, incorporating validation.",
      "Utilized RxJS for real-time data updates and component communication.",
      "Handled API failures with Angular’s ErrorInterceptor and Toast notifications.",
      "Followed Agile methodology, tracked tasks with Jira, and maintained version control with Git.",
    ],
    tools: ["Angular 13", "HTML 5", "CSS 3", "Bootstrap 5", "Git", "Jira"],
  },
  {
    company: "Techdeets Info Solutions Pvt Ltd",

    client: "USM Systems",
    role: "UI Developer",
    duration: "Oct 2020 to Sep 2021",
    description:
      "Consultant Information Management System is an Angular-based web application that streamlines consultant management by storing and accessing profiles, enabling easy search for consultants, managing assignments, tracking project allocations, and generating reports.",
    responsibilities: [
      "Designed and developed the user interface using React.js, creating reusable and modular components.",
      "Utilized React Hooks (useState, useEffect, useRef, useCallback) to manage state and lifecycle methods.",
      "Implemented React Router to manage navigation between views.",
      "Leveraged React’s Context API for global state management, enabling seamless data sharing.",
      "Built a custom component library using React and Styled-Components.",
      "Integrated RESTful APIs using Axios to fetch and update data from the backend.",
      "Developed dynamic forms using React Hook Form and Yup for validation.",
      "Optimized performance with React.memo, useMemo, and useCallback.",
      "Implemented unit tests using Jest and React Testing Library, conducted end-to-end testing with Cypress.",
    ],
    tools: ["React", "JavaScript", "Axios", "HTML 5", "CSS 3"],
  },
  {
    company: "Techdeets Info Solutions Pvt Ltd",

    client: "HIGHIQ Robotics India Pvt Ltd",
    role: "UI Developer",
    duration: "April 2019 to Oct 2020",
    description:
      "Parivartan - Dream of India is an initiative to make UPSC guidance accessible and affordable for aspiring civil servants.",
    responsibilities: [
      "Designed and developed scalable front-end architecture using Angular11.",
      "Built reusable and dynamic Angular components to streamline development.",
      "Implemented state management using Angular services and RxJS.",
      "Configured Angular Router for smooth navigation.",
      "Ensured cross-browser compatibility and responsive design.",
      "Developed and consumed RESTful APIs and GraphQL endpoints.",
      "Implemented dynamic, validated forms with Angular Forms.",
      "Collaborated with designers to implement responsive interfaces using Angular Material.",
      "Wrote unit tests for Angular components and services using Jasmine and Karma.",
      "Deployed applications to Azure cloud using PaaS services.",
    ],
    tools: [
      "Angular 11",
      "HTML5",
      "CSS3",
      "JavaScript",
      "TypeScript",
      "RxJS",
      "Angular Material",
      "RESTful APIs",
      "Jasmine",
      "Karma",
    ],
  },
  {
    company: "Apollo Groups",

    client: "Apollo Groups",
    role: "Junior Web Developer",
    duration: "May 2017 to April 2019",
    description:
      "Healthcare Patient Management System is a web application that streamlines patient records management, ensuring accessibility for healthcare professionals.",
    responsibilities: [
      "Designed and developed mobile-friendly web pages using HTML5, CSS3, and JavaScript.",
      "Collaborated with designers and backend developers to create responsive UI components.",
      "Troubleshot and debugged front-end development issues.",
      "Worked with the testing team to ensure functionality of UI components.",
      "Stayed updated with the latest front-end development trends.",
    ],
    tools: ["HTML5", "CSS3", "JavaScript"],
  },
];
